# Generated by Django 5.1.7 on 2025-03-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_listed', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
            ],
        ),
    ]
