# Generated by Django 5.1.7 on 2025-03-16 15:21

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWithImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_listed', models.BooleanField(default=False)),
                ('image1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image1')),
                ('image2', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image2')),
                ('image3', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image3')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
